language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

install: travis_retry composer install

script: if [[ "`phpenv version-name`" != "7.3" ]]; then make travis; fi

after_success:
  - if [[ "`phpenv version-name`" != "7.3" ]]; then exit 0; fi
  - vendor/bin/phpunit --printer="PHPUnit\TextUI\ResultPrinter" --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
