language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

sudo: false

install: travis_retry composer install

before_script: composer install --prefer-source

script: composer ci

cache:
  directories:
    - $HOME/.composer/cache